version: '3.0'
services:
  frontend:
    container_name: app_frontend
    build: ./front-end
    ports:
      - 3000:3000
    working_dir: /app-frontend
    volumes:
      - ./front-end/src:/app-frontend/src
    networks:
      - my_network
    depends_on:
      - backend
    

  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    working_dir: /app-backend
    tty: true
    stdin_open: true
    command: dev
    depends_on:
      - db
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
    volumes:
      - ./back-end/src:/app-backend/src
    networks:
      - my_network

  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=RECIPES_APP
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always
    cap_add:
      - SYS_NICE
    networks:
      - my_network

networks:
  my_network: 

